### ISSUE TITLE
Issues with non-ascii characters in issue title

### ISSUE THREAD

**Issue by cuerty** [pignacio/issue2branch#20]
Using the git backend:

Traceback (most recent call last):
  File "/usr/local/bin/issue2branch", line 9, in <module>
    load_entry_point('issue2branch==0.0.2', 'console_scripts', 'issue2branch')()
  File "/usr/local/lib/python2.7/dist-packages/issue2branch/__init__.py", line 7, in main
    get_issue_tracker(config).run()
  File "/usr/local/lib/python2.7/dist-packages/issue2branch/trackers/base.py", line 121, in run
    self._list_issues(issues)
  File "/usr/local/lib/python2.7/dist-packages/issue2branch/trackers/base.py", line 142, in _list_issues
    print "{} * {}".format("  " * indent, issue.text())
  File "/usr/local/lib/python2.7/dist-packages/issue2branch/issue.py", line 35, in text
    self.title, assignee)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 52: ordinal not in range(128)

In this case the title of the issue was:

> after you include the referral name/email and click “SEND”, the name/email doesn’t disappear

**Comment by pignacio** [comment]
This should be fixed in version 0.0.7
