### ISSUE TITLE
Github issues return 404 if the remote has ".git" at the end

### ISSUE THREAD

**Issue by pignacio** [pignacio/issue2branch#21]
With

```
[vld_django]verne :: pignacio/vld_django/vld_django ‹master› % git remote -v                           1 ↵
origin	git@github.com:pignacio/vld_django.git (fetch)
origin	git@github.com:pignacio/vld_django.git (push)
```

`issue2branch -l` returns

```
[vld_django]verne :: pignacio/vld_django/vld_django ‹master› % issue2branch -l                            
Loading issue2branch config from: '/home/ignacio/src/pignacio/vld_django/.issue2branch.config'
Got an InsecurePlatformWarning. Upgrade python to 2.7.9 or better to remove.
Traceback (most recent call last):
  File "/home/ignacio/.local/bin/issue2branch", line 9, in <module>
    load_entry_point('issue2branch==0.0.7', 'console_scripts', 'issue2branch')()
  File "/home/ignacio/src/pignacio/issue2branch/issue2branch/__init__.py", line 18, in main
    get_issue_tracker(config).run(config)
  File "/home/ignacio/src/pignacio/issue2branch/issue2branch/trackers/base.py", line 124, in run
    issues = self.get_issue_list(config, options)
  File "/home/ignacio/src/pignacio/issue2branch/issue2branch/trackers/base.py", line 52, in get_issue_list
    response = self._request(requests.get, url)
  File "/home/ignacio/src/pignacio/issue2branch/issue2branch/trackers/base.py", line 42, in _request
    **kwargs)
  File "/home/ignacio/src/pignacio/issue2branch/issue2branch/utils/requests.py", line 69, in request
    ), response)
issue2branch.utils.requests.NotOkResponse: Response status code for 'https://api.github.com/repos/pignacio/vld_django.git/issues?per_page=40' was not 2xx: 404. Authenticated: False
```

We should be careful with repos that actually end in `.git`

**Comment by pignacio** [comment]
Apparently you can't create repos ending in `.git` in github. Yay, easy peasy
